### ISSUE TITLE
Is there a way I can add force torque sensor?

### ISSUE THREAD

**Issue by KhalilAbuibaid** [HoangGiang93/mujoco_sim#1]
I'm updating the model from ur5 to ur5e, therefoe I'm looking forward recieving the data from the force and torque sensors in the sixth axis.   Is there any way I could do that?

**Comment by HoangGiang93** [comment]
> I'm updated the model from ur5 to ur5e, therefoe I'm looking forward recieving the data from the force and torque sensors in the six axis. Is there any way I could do that?

Currently it isn't implemented yet. However you can make a request and I will implement it soon. I assume that you want to have a force/torque sensor that output the data using ROS, which rosmsg are you gonna use?

**Comment by KhalilAbuibaid** [comment]
The assumption you did is right. If not mistaken, the real hardware of ur5e publish float64 in xyz for force and torque. Thanks alot in advance!

**Comment by HoangGiang93** [comment]
Ok so there is no specific rosmsg for force/torque sensor that you wanna use right?

**Comment by KhalilAbuibaid** [comment]
Not really no specific one

**Comment by HoangGiang93** [comment]
Now you can add force torque sensor, just add a tag `site` to the link you want to mount the sensor and add the sensors with the corresponding site. The sensor messages will be published on topic `/mujoco/sensors_3D`
See https://github.com/HoangGiang93/mujoco_robots/blob/main/franka/franka_mujoco/model/panda_arm.xml#L57 and https://github.com/HoangGiang93/mujoco_robots/blob/main/franka/franka_mujoco/model/panda_arm.xml#L68-L71.

**Comment by KhalilAbuibaid** [comment]
Thanks alot for the effort!
