### ISSUE TITLE
Driving robot with controllers

### ISSUE THREAD

**Issue by AlexGisi** [HoangGiang93/mujoco_sim#21]
Hello, thank you for the excellent library. I am trying to drive a [Clearpath Jackal](https://github.com/jackal/jackal/tree/noetic-devel) with the controllers provided in that repo, but the robot is not moving. I was wondering if I am doing something obviously wrong.

Here are the steps I took:

1. Generate a URDF from the xacro provided [here](https://github.com/jackal/jackal/blob/noetic-devel/jackal_description/urdf/jackal.urdf.xacro). 
2. Edit `mujoco_simsrc/config/robot.yaml`, making the changes

```
add_odom_joints: true
root_frame_id: odom
```

4. Start the controller with `roslaunch jackal_control control.launch`. 
5. Start the simulation with `roslaunch mujoco_sim mujoco_sim.launch robot:=/my/path/test.urdf use_urdf:=true`.
6. Observe the odometry is working as expected (`rostopic echo /odometry/filtered`) and the `/mujoco_sim` node is subscribed to the `/jackal_velocity_controller/cmd_vel` topic:

```
> rostopic info /jackal_velocity_controller/cmd_vel
Type: geometry_msgs/Twist

Publishers: 
 * /twist_mux (http://alex-laptop:39041/)

Subscribers: 
 * /mujoco_sim (http://alex-laptop:39363/)
 ```
7. But when publishing velocity commands:
```
rostopic pub /jackal_velocity_controller/cmd_vel geometry_msgs/Twist "{linear: {x: 1.0, y: 0.0, z: 0.0}, angular: {x: 0.0, y: 0.0, z: 0.0}}" -r 10
```
the robot does not respond. The robot can still be moved directly:

```
rostopic pub /jackal/cmd_vel geometry_msgs/Twist "{linear: {x: 1.0, y: 0.0, z: 0.0}, angular: {x: 0.0, y: 0.0, z: 0.5}}" -r 10
```

Would you have any insight into where I'm misguided?

**Comment by HoangGiang93** [comment]
Did you check with
`rostopic echo /jackal/cmd_vel`
when you do
`rostopic pub /jackal_velocity_controller/cmd_vel geometry_msgs/Twist "{linear: {x: 1.0, y: 0.0, z: 0.0}, angular: {x: 0.0, y: 0.0, z: 0.0}}" -r 10`
?
Could you also do
`rosnode info /mujoco_sim`
to see if it actually connects to your topic?

**Comment by AlexGisi** [comment]
Thanks for the response. I now see that the original twist_mux publisher /jackal_velocity_controller/cmd_vel must be remapped to /jackal/cmd_vel in order to be received by the mujoco_sim node.

My underlying question related to simulating the response of the jackal hardware to the velocity commands. Presently, when I published to /jackal/cmd_vel, the robot instantly obtains the requested speed (e.g. 10 m/s). Clearly, the wheel contacts are not being simulated (they would slip) nor are the wheel joints (the requested speeds exceed the joint limits). 

Examining the code, I do not understand how the controllers (e.g. diff_drive_controller) interface with the hardware interface (as shown in the picture below). Is that interaction hidden?

![control-loop](https://github.com/user-attachments/assets/66293611-442c-4cc7-aff4-fe55d3a6b627)

Maybe I have some misconceptions on how to use the system!

**Comment by HoangGiang93** [comment]
Ok first off, the /cmd_vel has nothing to do with the ros_control. It's something I implemented to simplify the base controller without having another "controller" for the wheel to move the base according to the commanded velocity. The principle is also simple, for the diff_drive_controller, I only added three virtual joints (odom_lin_x, odom_lin_y and odom ang_z) to the base, making it moving with three degree of freedom. The rest is to map the control signal to the velocity.

About how the controllers interface with the hardware interface. If you use e.g. joint_trajectory_controller, you can see that by changing the type, you can make it position, velocity or effort-based controller. The actual implementation is indeed hidden in the hardware interface (hence it calls "hardware _interface_"), making it flexible to change in runtime.

For my package, [here](https://github.com/HoangGiang93/mujoco_sim/blob/main/src/mujoco_sim/mj_hw_interface.cpp) is how I implemented the hardware interface.

Hope it helps.

**Comment by AlexGisi** [comment]
I see. I identified one source of my problem, which was the model file being generated by the urdf->xml compilation process. That model was not suitable for my purpose (e.g. it lacked actuators at the wheels). I replaced it with a hand-make jackal model file, which has four hinge joints representing wheels.

This means when the virtual joints are added, the robot has more than 6-dof which is unacceptable to mujoco. Disabling the virtual odometry joints allows the robot to spawn, but then I am not sure how to communicate with the controllers.

I used the following robot and world files:

[jackal_robot.xml](https://github.com/user-attachments/files/16367087/jackal_robot.txt)
[jackal_world.xml](https://github.com/user-attachments/files/16367090/jackal_world.txt)

**Comment by HoangGiang93** [comment]
you can control the wheel using the velocity_controller interface from ros_control. You just need to specify the yaml file including all wheels and the corresponding controllers.

**Comment by AlexGisi** [comment]
I can apparently load the `diff_drive_controller` (which is the controller I want to use), but I do not understand the resulting behavior. My control.yaml is

```
jackal_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

jackal_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['front_left_wheel', 'rear_left_wheel']
  right_wheel: ['front_right_wheel', 'rear_right_wheel']
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
  cmd_vel_timeout: 0.25

...
```

**But the commands I send don't seem to be subject to any control loop or hardware simulation. They are just directly enacted upon the robot state.** 

This occurs whether or not the controllers are loaded: I attached videos below of publishing an "unrealistic" command, which is immediately met.

Without controllers:
[no-controller.webm](https://github.com/user-attachments/assets/929a1e5a-95d9-4a73-933c-7da03e62f303)

With controllers:
[with-controller.webm](https://github.com/user-attachments/assets/0253dd0a-dc9d-47e0-b78a-c07bcbbf3463)

Is this really the expected behavior?

**Comment by HoangGiang93** [comment]
Looks like so, did you disable the virtual odometry joints? You can set angular velocity lower and see if the wheels are rotating. The unit is radian, so 55rad/s is quite big.

**Comment by AlexGisi** [comment]
The above example included the virtual odometry joints. I was just surprised the control limits set in `control.yaml` aren't being respected.

**Comment by HoangGiang93** [comment]
Well if you want to control the base via the wheel, then you should exclude the virtual odom joints, otherwise your wheels dont do anything

**Comment by HoangGiang93** [comment]
Set the `add_odom_joints` to `false` in the yaml file like in [this](https://github.com/HoangGiang93/mujoco_sim/blob/main/src/config/robot.yaml#L17).

**Comment by AlexGisi** [comment]
Hi Giang,

The issue was with line 651 in mj_ros.cpp, which is the predicate for adding controlled joints:

```
if (controller_state.state.compare("running") == 0 && (controller_state.type.find("position_controllers") != std::string::npos || controller_state.type.find("velocity_controllers") != std::string::npos || controller_state.type.find("effort_controllers") != std::string::npos)
```

The Jackal's `diff_drive_controller/DiffDriveController` was not triggering this statement, so I had to add `controller_state.type.find("diff_drive_controller/DiffDriveController") != std::string::npos` to the list of conditions. 

Also, the order of running the launch files was quite specific, and perhaps should be documented somewhere:

```
roslaunch mujoco_sim mujoco_sim.launch robot:=<path to xml>
roslaunch jackal_description description.launch
roslaunch jackal_control control.launch
```

Finally, I'd like to note the `sensornoise="disable"` tag in line 3 of `empty.xml` causes an error on loading the model and is not mentioned in the [xml documentation](https://mujoco.readthedocs.io/en/stable/XMLreference.html), so should probably be removed.

I could make a pull request for these changes if you would like?

**Comment by HoangGiang93** [comment]
I'm glad it worked out for you. Please make a pull request.
