### ISSUE TITLE
Integration issues between MJCF format and ROS controllers

### ISSUE THREAD

**Issue by ljy667** [HoangGiang93/mujoco_sim#25]
Hello, if I want to import a robot model using the MJCF format, can I still use the controller interfaces, controller managers, and hardware interfaces sourced from http://wiki.ros.org/ros_control

**Comment by HoangGiang93** [comment]
Yes you can, as I've written in this [tutorial](https://github.com/HoangGiang93/mujoco_sim/wiki/2.-Control-the-arm,-gripper-and-base-of-a-robot).

**Comment by ljy667** [comment]
Thank you for your answer. Let me study it

**Comment by ljy667** [comment]
Thank you for your answer. Let me study it
